apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
#  type: NodePort
  type: LoadBalancer
  ports:
  - name: web
    port: 80
    targetPort: 3000
#    protocol: TCP
#    nodePort: 30902
  selector:
    app: grafana
