apiVersion: v1
kind: Service
metadata:
  name: prediction-java
  labels:
    app: prediction-java
    hystrix.enabled: "true"
#  annotations:
#    dns.alpha.kubernetes.io/external: prediction-java.your.domain.com
spec:
  type: LoadBalancer
  ports:
  - name: prediction-java
    port: 80 
    targetPort: 9040 
  selector:
    app: prediction-java
    hystrix.enabled: "true" 
