apiVersion: v1
kind: Service
metadata:
  name: prediction-keyvalue
  labels:
    app: prediction-keyvalue
    hystrix.enabled: "true"
#  annotations:
#    dns.alpha.kubernetes.io/external: prediction-keyvalue.your.domain.com
spec:
  type: LoadBalancer
  ports:
  - name: prediction-keyvalue
    port: 80 
    targetPort: 9040 
  selector:
    app: prediction-keyvalue
    hystrix.enabled: "true" 
