apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prediction-spark
  labels:
    app: prediction-spark
    hystrix.enabled: "true"
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: prediction-spark
  template:
    metadata:
      labels:
        app: prediction-spark
        hystrix.enabled: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/prometheus"
        prometheus.io/port: "9040"
    spec:
      containers:
      - name: prediction-spark
        image: docker.io/primedio/prediction-spark:master
        resources:
          limits:
            cpu: 8000m
            memory: 8000Mi
          requests:
            cpu: 1000m
            memory: 1000Mi 
        imagePullPolicy: "Always"
        env:
        ports:
        - containerPort: 9040
        volumeMounts:
          - name: git-volume
            mountPath: /root/volumes
      volumes:
        - name: git-volume
          gitRepo:
            repository: "https://github.com/fluxcapacitor/source.ml.git"
            revision: "master"

