apiVersion: v1
kind: Service
metadata:
  name: prediction-tensorflow
  labels:
    app: prediction-tensorflow
    hystrix.enabled: "true"
#  annotations:
#    dns.alpha.kubernetes.io/external: prediction-tensorflow.your.domain.com
spec:
  type: LoadBalancer
  ports:
  - name: prediction-tensorflow
    port: 80 
    targetPort: 9040
  selector:
    app: prediction-tensorflow
    hystrix.enabled: "true"
