apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver-prometheus-discovery
  labels:
    k8s-app: kubernetes
spec:
  selector:
    k8s-app: kube-apiserver
  type: ClusterIP
  clusterIP: None
  ports:
  - name: https-metrics
    port: 443
    targetPort: 443
    protocol: TCP
