apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch-2-3-0
  labels:
    app: elasticsearch-2-3-0
spec:
  replicas: 1
  selector:
    name: elasticsearch-2-3-0
  template:
    metadata:
      labels:
        name: elasticsearch-2-3-0
    spec:
      containers:
      - name: elasticsearch-2-3-0
        image: docker.io/primedio/elasticsearch-2.3.0:master
        imagePullPolicy: "Always"
        ports:
        - containerPort: 9200
        - containerPort: 9300
