apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver-prometheus-discovery
  labels:
    k8s-app: kubernetes
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: https-metrics
    port: 8443
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kube-apiserver-prometheus-discovery
  labels:
    k8s-app: kubernetes
subsets:
- addresses:
  - ip: 192.168.99.100
  ports:
  - name: https-metrics
    port: 8443
    protocol: TCP
